import type { IRProgram } from "../ir.js";
import type { TypeRef } from "../types.js";
import {
  emitFunctions,
  emitModels,
  type GeneratedFile,
} from "./vue.js";

export function emitAI(program: IRProgram): readonly GeneratedFile[] {
  if (program.agents.length === 0) {
    throw new Error("The ai target requires at least one agent declaration.");
  }

  return [
    {
      path: "package.json",
      content:
        JSON.stringify(
          {
            name: slug(program.appName) + "-ai",
            private: true,
            version: "0.0.0",
            type: "module",
            scripts: {
              build: "tsc -p tsconfig.json",
              test: "npm run build && node dist/evaluations.js",
            },
            devDependencies: {
              "@types/node": "^24.0.0",
              typescript: "^5.9.0",
            },
          },
          null,
          2,
        ) + "\n",
    },
    {
      path: "tsconfig.json",
      content:
        JSON.stringify(
          {
            compilerOptions: {
              target: "ES2022",
              module: "NodeNext",
              moduleResolution: "NodeNext",
              strict: true,
              outDir: "dist",
              rootDir: "src",
              skipLibCheck: true,
            },
            include: ["src/**/*.ts"],
          },
          null,
          2,
        ) + "\n",
    },
    {
      path: "src/generated/models.ts",
      content: emitModels(
        program.data,
        program.classes,
        program.protocols,
        program.choices,
      ),
    },
    {
      path: "src/generated/functions.ts",
      content: emitFunctions(
        program.functions,
        program.data,
        program.classes,
      ).replaceAll('from "./models"', 'from "./models.js"'),
    },
    {
      path: "src/generated/schemas.ts",
      content: emitSchemas(program),
    },
    {
      path: "src/generated/runtime.ts",
      content: emitRuntime(program),
    },
    {
      path: "src/evaluations.ts",
      content: emitEvaluations(program),
    },
    {
      path: "src/generated/evermore.ai.json",
      content:
        JSON.stringify(
          {
            app: program.appName,
            target: "ai",
            agents: program.agents,
            tools: program.tools,
            contexts: program.contexts,
            evaluations: program.evaluations,
          },
          null,
          2,
        ) + "\n",
    },
  ];
}

function emitSchemas(program: IRProgram): string {
  const entries: string[] = [];

  for (const model of program.data) {
    entries.push(
      "  " +
        JSON.stringify(model.name) +
        ": " +
        objectSchema(model.fields) +
        ",",
    );
  }

  for (const model of program.classes) {
    entries.push(
      "  " +
        JSON.stringify(model.name) +
        ": " +
        objectSchema(
          model.fields.filter((field) => field.visibility === "public"),
        ) +
        ",",
    );
  }

  for (const protocol of program.protocols) {
    entries.push(
      "  " +
        JSON.stringify(protocol.name) +
        ": " +
        objectSchema(protocol.fields) +
        ",",
    );
  }

  for (const choice of program.choices) {
    entries.push(
      "  " +
        JSON.stringify(choice.name) +
        ': { kind: "choice", cases: ' +
        JSON.stringify(choice.cases) +
        " },",
    );
  }

  return [
    "// Generated by Evermore. Do not edit by hand.",
    "",
    "export type ContractSchema =",
    '  | { readonly kind: "primitive"; readonly name: "text" | "id" | "number" | "boolean" }',
    '  | { readonly kind: "choice"; readonly cases: readonly string[] }',
    '  | { readonly kind: "object"; readonly fields: Readonly<Record<string, ContractSchema>> }',
    '  | { readonly kind: "list"; readonly element: ContractSchema }',
    '  | { readonly kind: "set"; readonly element: ContractSchema }',
    '  | { readonly kind: "map"; readonly key: ContractSchema; readonly value: ContractSchema }',
    '  | { readonly kind: "optional"; readonly value: ContractSchema }',
    '  | { readonly kind: "result"; readonly ok: ContractSchema; readonly error: ContractSchema }',
    '  | { readonly kind: "named"; readonly name: string };',
    "",
    "export const evermoreSchemas: Readonly<Record<string, ContractSchema>> = {",
    ...entries,
    "} as const;",
    "",
    "export function validateEvermoreValue(value: unknown, schema: ContractSchema): boolean {",
    "  switch (schema.kind) {",
    '    case "primitive":',
    '      if (schema.name === "number") return typeof value === "number" && Number.isFinite(value);',
    '      if (schema.name === "boolean") return typeof value === "boolean";',
    '      return typeof value === "string";',
    '    case "choice":',
    '      return typeof value === "string" && schema.cases.includes(value);',
    '    case "object":',
    '      return typeof value === "object" && value !== null &&',
    '        Object.entries(schema.fields).every(([key, child]) =>',
    '          validateEvermoreValue((value as Record<string, unknown>)[key], child));',
    '    case "list":',
    '      return Array.isArray(value) && value.every((item) => validateEvermoreValue(item, schema.element));',
    '    case "set":',
    '      return (Array.isArray(value) || value instanceof Set) &&',
    '        [...value].every((item) => validateEvermoreValue(item, schema.element));',
    '    case "map":',
    '      if (value instanceof Map) return [...value.entries()].every(([key, child]) =>',
    '        validateEvermoreValue(key, schema.key) && validateEvermoreValue(child, schema.value));',
    '      return typeof value === "object" && value !== null &&',
    '        Object.entries(value).every(([key, child]) =>',
    '          validateEvermoreValue(key, schema.key) && validateEvermoreValue(child, schema.value));',
    '    case "optional":',
    '      return value === null || validateEvermoreValue(value, schema.value);',
    '    case "result":',
    '      return typeof value === "object" && value !== null &&',
    '        (((value as { kind?: unknown }).kind === "ok" &&',
    '          validateEvermoreValue((value as { value?: unknown }).value, schema.ok)) ||',
    '         ((value as { kind?: unknown }).kind === "error" &&',
    '          validateEvermoreValue((value as { error?: unknown }).error, schema.error)));',
    '    case "named": {',
    '      const target = evermoreSchemas[schema.name];',
    '      return target ? validateEvermoreValue(value, target) : false;',
    "    }",
    "  }",
    "}",
    "",
  ].join("\n");
}

function emitRuntime(program: IRProgram): string {
  const agents = program.agents.map((agent) => ({
    name: agent.name,
    inputSchema: schemaObject(agent.inputType),
    outputSchema: schemaObject(agent.outputType),
    model: agent.modelRequirement,
    context: agent.contextName ?? null,
    tools: agent.tools,
    approvals: agent.approvalTools,
    tokenBudget: agent.tokenBudget,
    costBudget: agent.costBudget ?? null,
    tracing: agent.tracing,
  }));

  const tools = program.tools.map((tool) => ({
    name: tool.name,
    inputSchema: tool.inputType ? schemaObject(tool.inputType) : null,
    outputSchema: schemaObject(tool.outputType),
    permission: tool.permission,
    handler: tool.handler,
  }));

  const contexts = program.contexts.map((context) => ({
    name: context.name,
    includes: context.includes,
    tokenBudget: context.tokenBudget,
    overflow: context.overflow,
  }));

  return [
    "// Generated by Evermore. Do not edit by hand.",
    'import { evermoreFunctions } from "./functions.js";',
    'import { validateEvermoreValue, type ContractSchema } from "./schemas.js";',
    "",
    'export type EvermoreTraceEvent = { readonly type: "agent.start" | "agent.end" | "tool.start" | "tool.end"; readonly agent: string; readonly tool?: string; readonly data?: unknown };',
    'export type EvermoreModelRequest = { readonly agent: string; readonly modelRequirement: string; readonly input: unknown; readonly context: readonly { readonly source: string; readonly value: unknown }[]; readonly tools: readonly { readonly name: string; readonly permission: string; readonly requiresApproval: boolean }[]; readonly budget: { readonly tokens: number; readonly cost?: number } };',
    'export type EvermoreModelResponse = { readonly output: unknown; readonly usage: { readonly tokens: number; readonly cost?: number } };',
    'export interface EvermoreModelProvider { run(request: EvermoreModelRequest, callTool: (name: string, input: unknown) => Promise<unknown>): Promise<EvermoreModelResponse>; }',
    'export type EvermoreAgentDependencies = { readonly provider: EvermoreModelProvider; readonly context?: (source: string) => Promise<unknown> | unknown; readonly approve?: (agent: string, tool: string, input: unknown) => Promise<boolean> | boolean; readonly trace?: (event: EvermoreTraceEvent) => void; readonly toolOverrides?: Readonly<Record<string, (input: unknown) => Promise<unknown> | unknown>> };',
    "",
    "const agents = " + JSON.stringify(agents, null, 2) + " as const;",
    "const tools = " + JSON.stringify(tools, null, 2) + " as const;",
    'const contexts: readonly { readonly name: string; readonly includes: readonly string[]; readonly tokenBudget: number; readonly overflow: "summarize" | "reject" }[] = ' + JSON.stringify(contexts, null, 2) + ";",
    "",
    "function agentSpec(name: string) { const spec = agents.find((item) => item.name === name); if (!spec) throw new Error(\"Unknown Evermore agent \" + name); return spec; }",
    "function toolSpec(name: string) { const spec = tools.find((item) => item.name === name); if (!spec) throw new Error(\"Unknown Evermore tool \" + name); return spec; }",
    "function contextSpec(name: string | null) { if (!name) return undefined; const spec = contexts.find((item) => item.name === name); if (!spec) throw new Error(\"Unknown Evermore context \" + name); return spec; }",
    "function estimateTokens(value: unknown): number { return Math.max(1, Math.ceil(JSON.stringify(value).length / 4)); }",
    "",
    "async function buildContext(name: string | null, deps: EvermoreAgentDependencies): Promise<readonly { readonly source: string; readonly value: unknown }[]> {",
    "  const spec = contextSpec(name);",
    "  if (!spec || !deps.context) return [];",
    "  const resolved: { source: string; value: unknown }[] = [];",
    "  let used = 0;",
    "  for (const source of spec.includes) {",
    "    const value = await deps.context(source);",
    "    const tokens = estimateTokens(value);",
    "    if (used + tokens <= spec.tokenBudget) { resolved.push({ source, value }); used += tokens; continue; }",
    '    if (spec.overflow === "reject") throw new Error("Evermore context budget exceeded for " + spec.name);',
    "    const remaining = Math.max(0, spec.tokenBudget - used);",
    "    resolved.push({ source, value: { evermoreSummary: JSON.stringify(value).slice(0, remaining * 4), truncated: true } });",
    "    break;",
    "  }",
    "  return resolved;",
    "}",
    "",
    "export async function executeEvermoreTool(agentName: string, toolName: string, input: unknown, deps: EvermoreAgentDependencies): Promise<unknown> {",
    "  const agent = agentSpec(agentName);",
    "  if (!(agent.tools as readonly string[]).includes(toolName)) throw new Error(\"Agent \" + agentName + \" does not have capability for tool \" + toolName);",
    "  const tool = toolSpec(toolName);",
    "  if (tool.inputSchema && !validateEvermoreValue(input, tool.inputSchema as ContractSchema)) throw new Error(\"Invalid input for Evermore tool \" + toolName);",
    "  if ((agent.approvals as readonly string[]).includes(toolName)) {",
    "    const approved = deps.approve ? await deps.approve(agentName, toolName, input) : false;",
    "    if (!approved) throw new Error(\"Human approval denied or missing for tool \" + toolName);",
    "  }",
    '  if (agent.tracing) deps.trace?.({ type: "tool.start", agent: agentName, tool: toolName, data: input });',
    "  const override = deps.toolOverrides?.[toolName];",
    "  const handler = evermoreFunctions[tool.handler as keyof typeof evermoreFunctions] as unknown as ((value?: unknown) => unknown);",
    "  const output = override ? await override(input) : await Promise.resolve(tool.inputSchema ? handler(input) : handler());",
    "  if (!validateEvermoreValue(output, tool.outputSchema as ContractSchema)) throw new Error(\"Invalid output from Evermore tool \" + toolName);",
    '  if (agent.tracing) deps.trace?.({ type: "tool.end", agent: agentName, tool: toolName, data: output });',
    "  return output;",
    "}",
    "",
    "export async function executeEvermoreAgent(agentName: string, input: unknown, deps: EvermoreAgentDependencies): Promise<unknown> {",
    "  const agent = agentSpec(agentName);",
    "  if (!validateEvermoreValue(input, agent.inputSchema as ContractSchema)) throw new Error(\"Invalid input for Evermore agent \" + agentName);",
    "  const context = await buildContext(agent.context, deps);",
    '  if (agent.tracing) deps.trace?.({ type: "agent.start", agent: agentName, data: input });',
    "  const response = await deps.provider.run({",
    "    agent: agent.name, modelRequirement: agent.model, input, context,",
    "    tools: agent.tools.map((name) => { const tool = toolSpec(name); return { name, permission: tool.permission, requiresApproval: (agent.approvals as readonly string[]).includes(name) }; }),",
    "    budget: { tokens: agent.tokenBudget, ...(agent.costBudget === null ? {} : { cost: agent.costBudget }) },",
    "  }, (tool, value) => executeEvermoreTool(agentName, tool, value, deps));",
    "  if (response.usage.tokens > agent.tokenBudget) throw new Error(\"Agent \" + agentName + \" exceeded token budget\");",
    "  if (agent.costBudget !== null && (response.usage.cost ?? 0) > agent.costBudget) throw new Error(\"Agent \" + agentName + \" exceeded cost budget\");",
    "  if (!validateEvermoreValue(response.output, agent.outputSchema as ContractSchema)) throw new Error(\"Agent \" + agentName + \" returned invalid structured output\");",
    '  if (agent.tracing) deps.trace?.({ type: "agent.end", agent: agentName, data: response.output });',
    "  return response.output;",
    "}",
    "",
    "export function createDeterministicModel(outputs: Readonly<Record<string, unknown>>): EvermoreModelProvider {",
    "  return { async run(request) {",
    '    if (!(request.agent in outputs)) throw new Error("No deterministic output configured for agent " + request.agent);',
    "    const output = outputs[request.agent];",
    "    return { output, usage: { tokens: estimateTokens(output) } };",
    "  } };",
    "}",
    "",
    "export function createDeterministicTools(outputs: Readonly<Record<string, unknown>>): Readonly<Record<string, (input: unknown) => unknown>> {",
    "  return Object.fromEntries(Object.entries(outputs).map(([name, value]) => [name, () => value]));",
    "}",
    "",
  ].join("\n");
}

function emitEvaluations(program: IRProgram): string {
  const lines = [
    "// Generated by Evermore. Do not edit by hand.",
    'import { evermoreFunctions } from "./generated/functions.js";',
    'import { createDeterministicModel, executeEvermoreAgent } from "./generated/runtime.js";',
    "",
    "let failures = 0;",
  ];

  for (const evaluation of program.evaluations) {
    lines.push(
      "{",
      "  const input = (evermoreFunctions[" +
        JSON.stringify(evaluation.inputFunction) +
        "] as unknown as () => unknown)();",
      "  const expected = (evermoreFunctions[" +
        JSON.stringify(evaluation.expectedFunction) +
        "] as unknown as () => unknown)();",
      "  const actual = await executeEvermoreAgent(" +
        JSON.stringify(evaluation.agentName) +
        ", input, {",
      "    provider: createDeterministicModel({ " +
        JSON.stringify(evaluation.agentName) +
        ": expected }),",
      "    approve: () => true,",
      "  });",
      "  if (JSON.stringify(actual) !== JSON.stringify(expected)) {",
      "    failures += 1;",
      "    console.error(" +
        JSON.stringify("Evaluation " + evaluation.name + " failed") +
        ");",
      "  } else {",
      "    console.log(" +
        JSON.stringify("✓ Evaluation " + evaluation.name) +
        ");",
      "  }",
      "}",
    );
  }

  lines.push("", "if (failures > 0) process.exitCode = 1;", "");
  return lines.join("\n");
}

function objectSchema(
  fields: readonly { readonly name: string; readonly type: TypeRef }[],
): string {
  return (
    '{ kind: "object", fields: { ' +
    fields
      .map(
        (field) =>
          JSON.stringify(field.name) + ": " + schemaLiteral(field.type),
      )
      .join(", ") +
    " } }"
  );
}

function schemaObject(type: TypeRef): unknown {
  return JSON.parse(schemaLiteral(type).replaceAll("'", '"'));
}

function schemaLiteral(type: TypeRef): string {
  switch (type.kind) {
    case "None":
      return '{"kind":"optional","value":{"kind":"named","name":"__never"}}';
    case "Primitive":
      return JSON.stringify({ kind: "primitive", name: type.name });
    case "Named":
    case "Protocol":
      return JSON.stringify({ kind: "named", name: type.name });
    case "Applied":
      return JSON.stringify({ kind: "named", name: type.name });
    case "Generic":
      return JSON.stringify({ kind: "named", name: "__generic" });
    case "List":
      return (
        '{"kind":"list","element":' +
        schemaLiteral(type.elementType) +
        "}"
      );
    case "Set":
      return (
        '{"kind":"set","element":' +
        schemaLiteral(type.elementType) +
        "}"
      );
    case "Map":
      return (
        '{"kind":"map","key":' +
        schemaLiteral(type.keyType) +
        ',"value":' +
        schemaLiteral(type.valueType) +
        "}"
      );
    case "Optional":
      return (
        '{"kind":"optional","value":' +
        schemaLiteral(type.valueType) +
        "}"
      );
    case "Result":
      return (
        '{"kind":"result","ok":' +
        schemaLiteral(type.okType) +
        ',"error":' +
        schemaLiteral(type.errorType) +
        "}"
      );
  }
}

function slug(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "evermore-ai"
  );
}
