import type { IRDeployment, IRProgram } from "../ir.js";
import type { GeneratedFile } from "./vue.js";

export function emitInfrastructure(
  program: IRProgram,
): readonly GeneratedFile[] {
  if (program.deployments.length === 0) {
    throw new Error(
      "The infra target requires at least one deploy declaration.",
    );
  }

  const files: GeneratedFile[] = [
    {
      path: "evermore.plan.json",
      content:
        JSON.stringify(
          {
            app: program.appName,
            target: "infra",
            mode: "plan",
            mutationRequiresExplicitApply: true,
            deployments: program.deployments.map((deployment) => ({
              name: deployment.name,
              server: deployment.serverName,
              image: deployment.image,
              replicas: deployment.replicas,
              port: deployment.port,
              health: deployment.healthPath,
              readiness: deployment.readinessPath,
              environmentSources: deployment.environments,
              secretReferences: deployment.secrets,
              observability: deployment.observability,
              rollbackRevisions: deployment.rollbackRevisions,
              policies: {
                pinnedImage: true,
                externalSecretsOnly: true,
                probesRequired: true,
                explicitApplyRequired: true,
              },
            })),
          },
          null,
          2,
        ) + "\n",
    },
  ];

  for (const deployment of program.deployments) {
    const directory = "deploy/" + slug(deployment.name);
    files.push(
      {
        path: directory + "/Dockerfile",
        content: emitDockerfile(deployment),
      },
      {
        path: directory + "/kubernetes.yaml",
        content: emitKubernetes(deployment),
      },
      {
        path: directory + "/plan.sh",
        content: emitPlanScript(),
      },
      {
        path: directory + "/apply.sh",
        content: emitApplyScript(deployment),
      },
      {
        path: directory + "/rollback.sh",
        content: emitRollbackScript(deployment),
      },
    );
  }

  return files;
}

function emitDockerfile(deployment: IRDeployment): string {
  return [
    "# Generated by Evermore for the generated Node target build context.",
    "FROM node:22-alpine AS build",
    "WORKDIR /app",
    "COPY package*.json ./",
    "RUN npm ci",
    "COPY . .",
    "RUN npm run build",
    "",
    "FROM node:22-alpine AS runtime",
    "ENV NODE_ENV=production",
    "WORKDIR /app",
    "COPY package*.json ./",
    "RUN npm ci --omit=dev",
    "COPY --from=build /app/dist ./dist",
    "EXPOSE " + deployment.port,
    'CMD ["npm", "start"]',
    "",
  ].join("\n");
}

function emitKubernetes(deployment: IRDeployment): string {
  const name = slug(deployment.name);
  const environmentLines = [
    ...deployment.environments.flatMap((item) => [
      "        - name: " + item.name,
      "          valueFrom:",
      "            configMapKeyRef:",
      "              name: " + name + "-config",
      "              key: " + yamlScalar(item.source),
    ]),
    ...deployment.secrets.flatMap((item) => [
      "        - name: " + item.name,
      "          valueFrom:",
      "            secretKeyRef:",
      "              name: " + name + "-secrets",
      "              key: " + yamlScalar(item.source),
    ]),
    ...(deployment.observability === "open-telemetry"
      ? [
          "        - name: OTEL_SERVICE_NAME",
          "          value: " + yamlScalar(deployment.serverName),
        ]
      : []),
  ];

  return [
    "apiVersion: apps/v1",
    "kind: Deployment",
    "metadata:",
    "  name: " + name,
    "  labels:",
    "    app.kubernetes.io/name: " + name,
    "    app.kubernetes.io/managed-by: evermore",
    "  annotations:",
    "    evermore.dev/observability: " + yamlScalar(deployment.observability),
    "spec:",
    "  replicas: " + deployment.replicas,
    "  revisionHistoryLimit: " + deployment.rollbackRevisions,
    "  selector:",
    "    matchLabels:",
    "      app.kubernetes.io/name: " + name,
    "  template:",
    "    metadata:",
    "      labels:",
    "        app.kubernetes.io/name: " + name,
    "        app.kubernetes.io/managed-by: evermore",
    "    spec:",
    "      containers:",
    "      - name: server",
    "        image: " + yamlScalar(deployment.image),
    "        imagePullPolicy: IfNotPresent",
    "        ports:",
    "        - name: http",
    "          containerPort: " + deployment.port,
    "        livenessProbe:",
    "          httpGet:",
    "            path: " + yamlScalar(deployment.healthPath),
    "            port: http",
    "        readinessProbe:",
    "          httpGet:",
    "            path: " + yamlScalar(deployment.readinessPath),
    "            port: http",
    ...(environmentLines.length > 0
      ? ["        env:", ...environmentLines]
      : []),
    "---",
    "apiVersion: v1",
    "kind: Service",
    "metadata:",
    "  name: " + name,
    "spec:",
    "  selector:",
    "    app.kubernetes.io/name: " + name,
    "  ports:",
    "  - name: http",
    "    port: " + deployment.port,
    "    targetPort: http",
    "",
  ].join("\n");
}

function emitPlanScript(): string {
  return [
    "#!/bin/sh",
    "set -eu",
    'cd "$(dirname "$0")"',
    'command -v kubectl >/dev/null 2>&1 || { echo "kubectl is required" >&2; exit 127; }',
    "kubectl apply --dry-run=server -f kubernetes.yaml",
    "",
  ].join("\n");
}

function emitApplyScript(deployment: IRDeployment): string {
  const name = slug(deployment.name);
  return [
    "#!/bin/sh",
    "set -eu",
    'cd "$(dirname "$0")"',
    'if [ "${EVERMORE_APPLY:-}" != "1" ]; then',
    '  echo "Refusing mutation. Set EVERMORE_APPLY=1 after reviewing the generated plan." >&2',
    "  exit 2",
    "fi",
    "kubectl apply -f kubernetes.yaml",
    "kubectl rollout status deployment/" + name,
    "",
  ].join("\n");
}

function emitRollbackScript(deployment: IRDeployment): string {
  const name = slug(deployment.name);
  return [
    "#!/bin/sh",
    "set -eu",
    'cd "$(dirname "$0")"',
    'if [ "${EVERMORE_APPLY:-}" != "1" ]; then',
    '  echo "Refusing rollback mutation. Set EVERMORE_APPLY=1 explicitly." >&2',
    "  exit 2",
    "fi",
    "kubectl rollout undo deployment/" + name,
    "",
  ].join("\n");
}

function yamlScalar(value: string): string {
  return JSON.stringify(value);
}

function slug(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "evermore"
  );
}
