import type {
  IRAction,
  IRElement,
  IRMobile,
  IRProgram,
  IRScreen,
} from "../ir.js";
import type { GeneratedFile } from "./vue.js";

export function emitReactNative(
  program: IRProgram,
): readonly GeneratedFile[] {
  const mobile = requireMobile(program);

  const files: GeneratedFile[] = [
    {
      path: "package.json",
      content:
        JSON.stringify(
          {
            name: slug(program.appName) + "-mobile",
            private: true,
            version: "0.0.0",
            scripts: {
              build: "tsc -p tsconfig.json --noEmit",
            },
            dependencies: {
              react: "^19.1.0",
              "react-native": "^0.81.0",
            },
            devDependencies: {
              "@types/react": "^19.1.0",
              typescript: "^5.9.0",
            },
          },
          null,
          2,
        ) + "\n",
    },
    {
      path: "tsconfig.json",
      content:
        JSON.stringify(
          {
            compilerOptions: {
              target: "ES2022",
              module: "ESNext",
              moduleResolution: "Bundler",
              jsx: "react-jsx",
              strict: true,
              noEmit: true,
              skipLibCheck: true,
              lib: ["ES2022"],
            },
            include: ["src/**/*.ts", "src/**/*.tsx"],
          },
          null,
          2,
        ) + "\n",
    },
    {
      path: "src/App.tsx",
      content: emitReactNativeApp(program),
    },
    {
      path: "src/generated/screens.tsx",
      content: emitReactNativeScreens(program.screens),
    },
    {
      path: "src/generated/mobile-runtime.ts",
      content: emitMobileRuntime(mobile),
    },
    {
      path: "src/generated/evermore.mobile.json",
      content: mobileManifest(program, mobile, "react-native"),
    },
  ];

  if (mobile.nativeExtensions.includes("swift")) {
    files.push({
      path: "ios/EvermoreNativeBridge.swift",
      content: emitSwiftBridge(mobile),
    });
  }

  if (mobile.nativeExtensions.includes("kotlin")) {
    files.push({
      path: "android/EvermoreNativeBridge.kt",
      content: emitKotlinBridge(mobile),
    });
  }

  return files;
}

export function emitFlutter(
  program: IRProgram,
): readonly GeneratedFile[] {
  const mobile = requireMobile(program);
  const files: GeneratedFile[] = [
    {
      path: "pubspec.yaml",
      content:
        "name: " +
        dartName(program.appName) +
        "\n" +
        'description: "Generated by Evermore"\n' +
        "publish_to: none\n" +
        "environment:\n" +
        '  sdk: ">=3.5.0 <4.0.0"\n' +
        "dependencies:\n" +
        "  flutter:\n" +
        "    sdk: flutter\n" +
        "flutter:\n" +
        "  uses-material-design: true\n",
    },
    {
      path: "lib/main.dart",
      content: emitFlutterApp(program),
    },
    {
      path: "lib/evermore_mobile.dart",
      content:
        "const evermoreStorage = " +
        JSON.stringify(mobile.storage) +
        ";\n" +
        "const evermoreNetwork = " +
        JSON.stringify(mobile.network) +
        ";\n" +
        "const evermorePermissions = <String>" +
        JSON.stringify(mobile.permissions).replace("[", "[").replace("]", "]") +
        ";\n",
    },
    {
      path: "evermore.mobile.json",
      content: mobileManifest(program, mobile, "flutter-experiment"),
    },
  ];

  if (mobile.nativeExtensions.includes("swift")) {
    files.push({
      path: "ios/Runner/EvermoreNativeBridge.swift",
      content: emitSwiftBridge(mobile),
    });
  }

  if (mobile.nativeExtensions.includes("kotlin")) {
    files.push({
      path: "android/app/src/main/kotlin/EvermoreNativeBridge.kt",
      content: emitKotlinBridge(mobile),
    });
  }

  return files;
}

function requireMobile(program: IRProgram): IRMobile {
  if (program.mobiles.length !== 1) {
    throw new Error(
      "Mobile targets require exactly one mobile declaration.",
    );
  }
  return program.mobiles[0]!;
}

function emitReactNativeApp(program: IRProgram): string {
  const first = program.screens[0]?.id ?? "Home";
  const imports = program.screens
    .map((screen) => screen.id + "Screen")
    .join(", ");

  const branches = program.screens
    .map(
      (screen) =>
        "  if (screen === " +
        JSON.stringify(screen.id) +
        ") return <" +
        screen.id +
        "Screen navigate={setScreen} />;",
    )
    .join("\n");

  return [
    'import React, { useState } from "react";',
    'import { SafeAreaView } from "react-native";',
    'import { ' + imports + ' } from "./generated/screens";',
    "",
    "export default function App() {",
    "  const [screen, setScreen] = useState(" + JSON.stringify(first) + ");",
    branches,
    "  return <SafeAreaView />;",
    "}",
    "",
  ].join("\n");
}

function emitReactNativeScreens(
  screens: readonly IRScreen[],
): string {
  return [
    'import React, { useState } from "react";',
    'import { Button, Text, View } from "react-native";',
    "",
    "export type EvermoreScreenProps = {",
    "  readonly navigate: (screen: string) => void;",
    "};",
    "",
    ...screens.map(emitReactNativeScreen),
  ].join("\n");
}

function emitReactNativeScreen(screen: IRScreen): string {
  const stateLines = screen.states.map(
    (state, index) =>
      "  const [state_" +
      index +
      ", setState_" +
      index +
      "] = useState(" +
      state.initialValue +
      ");",
  );
  const stateMap = new Map(
    screen.states.map((state, index) => [
      state.name,
      { value: "state_" + index, setter: "setState_" + index },
    ]),
  );

  return [
    "export function " +
      screen.id +
      "Screen({ navigate }: EvermoreScreenProps) {",
    ...stateLines,
    "  return (",
    '    <View style={{ flex: 1, padding: 24, gap: 12 }}>',
    ...(screen.title
      ? ["      <Text style={{ fontSize: 28, fontWeight: \"600\" }}>" +
          escapeJsx(screen.title) +
          "</Text>"]
      : []),
    ...screen.elements.map((element) =>
      emitReactNativeElement(element, stateMap, 3),
    ),
    "    </View>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function emitReactNativeElement(
  element: IRElement,
  states: ReadonlyMap<
    string,
    { readonly value: string; readonly setter: string }
  >,
  depth: number,
): string {
  const pad = "  ".repeat(depth);

  if (element.kind === "Text") {
    return pad + "<Text>" + escapeJsx(element.value) + "</Text>";
  }

  if (element.kind === "StateValue") {
    const state = states.get(element.stateName);
    return pad + "<Text>{" + (state?.value ?? "0") + "}</Text>";
  }

  if (element.kind === "Button") {
    return (
      pad +
      "<Button title=" +
      JSON.stringify(element.label) +
      " onPress={" +
      emitReactNativeAction(element.action, states) +
      "} />"
    );
  }

  const direction =
    element.direction === "horizontal" ? "row" : "column";

  return [
    pad +
      '<View style={{ flexDirection: "' +
      direction +
      '", gap: 12 }}>',
    ...element.elements.map((child) =>
      emitReactNativeElement(child, states, depth + 1),
    ),
    pad + "</View>",
  ].join("\n");
}

function emitReactNativeAction(
  action: IRAction | undefined,
  states: ReadonlyMap<
    string,
    { readonly value: string; readonly setter: string }
  >,
): string {
  if (!action) return "() => undefined";

  if (action.kind === "Navigate") {
    return "() => navigate(" + JSON.stringify(action.target) + ")";
  }

  const state = states.get(action.stateName);
  if (!state) return "() => undefined";

  return (
    "() => " +
    state.setter +
    "((value) => value + " +
    action.amount +
    ")"
  );
}

function emitMobileRuntime(mobile: IRMobile): string {
  return [
    'import { NativeModules } from "react-native";',
    "",
    "const memory = new Map<string, string>();",
    "const queued: { url: string; init?: RequestInit }[] = [];",
    "let online = true;",
    "export const evermorePermissions = " +
      JSON.stringify(mobile.permissions) +
      " as const;",
    "export const evermoreStorageMode = " +
      JSON.stringify(mobile.storage) +
      " as const;",
    "export const evermoreNetworkMode = " +
      JSON.stringify(mobile.network) +
      " as const;",
    "",
    "export async function evermoreStore(key: string, value: string): Promise<void> {",
    '  if (evermoreStorageMode === "secure" && NativeModules.EvermoreNativeStorage?.setItem) {',
    "    await NativeModules.EvermoreNativeStorage.setItem(key, value);",
    "    return;",
    "  }",
    "  memory.set(key, value);",
    "}",
    "",
    "export async function evermoreLoad(key: string): Promise<string | null> {",
    '  if (evermoreStorageMode === "secure" && NativeModules.EvermoreNativeStorage?.getItem) {',
    "    return (await NativeModules.EvermoreNativeStorage.getItem(key)) ?? null;",
    "  }",
    "  return memory.get(key) ?? null;",
    "}",
    "",
    "export async function evermoreRequestPermission(permission: string): Promise<boolean> {",
    "  if (!(evermorePermissions as readonly string[]).includes(permission)) {",
    '    throw new Error("Permission not declared in Evermore: " + permission);',
    "  }",
    "  if (!NativeModules.EvermoreNativePermissions?.request) return false;",
    "  return Boolean(await NativeModules.EvermoreNativePermissions.request(permission));",
    "}",
    "",
    "export function evermoreSetOnline(value: boolean): void {",
    "  online = value;",
    "}",
    "",
    "export async function evermoreFetch(url: string, init?: RequestInit): Promise<unknown> {",
    '  if (evermoreNetworkMode === "offline-first" && !online) {',
    "    queued.push({ url, ...(init ? { init } : {}) });",
    '    return { queued: true };',
    "  }",
    "  const response = await fetch(url, init);",
    "  return response.json();",
    "}",
    "",
    "export async function evermoreFlushNetworkQueue(): Promise<void> {",
    "  if (!online) return;",
    "  while (queued.length > 0) {",
    "    const item = queued.shift();",
    "    if (!item) break;",
    "    await fetch(item.url, item.init);",
    "  }",
    "}",
    "",
  ].join("\n");
}

function emitFlutterApp(program: IRProgram): string {
  const first = program.screens[0]?.id ?? "Home";
  const routes = program.screens
    .map(
      (screen) =>
        "        " +
        JSON.stringify("/" + screen.id) +
        ": (_) => const " +
        screen.id +
        "Screen(),",
    )
    .join("\n");

  const widgets = program.screens
    .map((screen) => emitFlutterScreen(screen))
    .join("\n\n");

  return [
    "import 'package:flutter/material.dart';",
    "",
    "void main() => runApp(const EvermoreApp());",
    "",
    "class EvermoreApp extends StatelessWidget {",
    "  const EvermoreApp({super.key});",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return MaterialApp(",
    "      initialRoute: " + JSON.stringify("/" + first) + ",",
    "      routes: {",
    routes,
    "      },",
    "    );",
    "  }",
    "}",
    "",
    widgets,
    "",
  ].join("\n");
}

function emitFlutterScreen(screen: IRScreen): string {
  const children: string[] = [];

  if (screen.title) {
    children.push(
      "            Text(" +
        JSON.stringify(screen.title) +
        ", style: const TextStyle(fontSize: 28, fontWeight: FontWeight.w600)),",
    );
  }

  for (const element of screen.elements) {
    if (element.kind === "Text") {
      children.push(
        "            Text(" + JSON.stringify(element.value) + "),",
      );
    } else if (element.kind === "Button") {
      const action =
        element.action?.kind === "Navigate"
          ? "Navigator.pushNamed(context, " +
            JSON.stringify("/" + element.action.target) +
            ");"
          : "";
      children.push(
        "            ElevatedButton(onPressed: () { " +
          action +
          " }, child: Text(" +
          JSON.stringify(element.label) +
          ")),",
      );
    }
  }

  return [
    "class " + screen.id + "Screen extends StatelessWidget {",
    "  const " + screen.id + "Screen({super.key});",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Scaffold(",
    "      body: SafeArea(",
    "        child: Padding(",
    "          padding: const EdgeInsets.all(24),",
    "          child: Column(",
    "            crossAxisAlignment: CrossAxisAlignment.start,",
    "            children: [",
    ...children,
    "            ],",
    "          ),",
    "        ),",
    "      ),",
    "    );",
    "  }",
    "}",
  ].join("\n");
}

function emitSwiftBridge(mobile: IRMobile): string {
  return [
    "import Foundation",
    "",
    "public protocol EvermoreNativeBridge {",
    "    func requestPermission(_ name: String) async -> Bool",
    "    func secureGet(_ key: String) async -> String?",
    "    func secureSet(_ key: String, value: String) async",
    "}",
    "",
    "public enum EvermoreNativePolicy {",
    "    public static let permissions = " +
      swiftArray(mobile.permissions),
    "}",
    "",
  ].join("\n");
}

function emitKotlinBridge(mobile: IRMobile): string {
  return [
    "package evermore.generated",
    "",
    "interface EvermoreNativeBridge {",
    "    suspend fun requestPermission(name: String): Boolean",
    "    suspend fun secureGet(key: String): String?",
    "    suspend fun secureSet(key: String, value: String)",
    "}",
    "",
    "object EvermoreNativePolicy {",
    "    val permissions: List<String> = listOf(" +
      mobile.permissions.map((item) => JSON.stringify(item)).join(", ") +
      ")",
    "}",
    "",
  ].join("\n");
}

function mobileManifest(
  program: IRProgram,
  mobile: IRMobile,
  target: string,
): string {
  return (
    JSON.stringify(
      {
        app: program.appName,
        target,
        mobile,
        screens: program.screens.map((screen) => screen.id),
      },
      null,
      2,
    ) + "\n"
  );
}

function swiftArray(values: readonly string[]): string {
  return (
    "[" +
    values.map((value) => JSON.stringify(value)).join(", ") +
    "]"
  );
}

function escapeJsx(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;");
}

function slug(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "evermore-mobile"
  );
}

function dartName(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") || "evermore_mobile"
  );
}
