import type {
  IRClassModel,
  IRDataModel,
  IRProgram,
  IRServer,
} from "../ir.js";
import type { TypeRef } from "../types.js";
import {
  emitFunctions,
  emitModels,
  emitTypeRef,
  type GeneratedFile,
} from "./vue.js";

export function emitNode(program: IRProgram): readonly GeneratedFile[] {
  if (program.servers.length === 0) {
    throw new Error(
      "The node target requires at least one server declaration.",
    );
  }

  const files: GeneratedFile[] = [
    {
      path: "package.json",
      content:
        JSON.stringify(
          {
            name: slug(program.appName) + "-server",
            private: true,
            version: "0.0.0",
            type: "module",
            scripts: {
              build: "tsc -p tsconfig.json",
              start: "node dist/index.js",
              dev: "tsx src/index.ts",
            },
            dependencies: {
              "node-cron": "^4.2.1",
              pg: "^8.16.3",
            },
            devDependencies: {
              "@types/node": "^24.0.0",
              "@types/pg": "^8.15.5",
              tsx: "^4.20.0",
              typescript: "^5.9.0",
            },
          },
          null,
          2,
        ) + "\n",
    },
    {
      path: "tsconfig.json",
      content:
        JSON.stringify(
          {
            compilerOptions: {
              target: "ES2022",
              module: "NodeNext",
              moduleResolution: "NodeNext",
              strict: true,
              outDir: "dist",
              rootDir: "src",
              skipLibCheck: true,
              esModuleInterop: true,
            },
            include: ["src/**/*.ts"],
          },
          null,
          2,
        ) + "\n",
    },
    {
      path: "src/generated/models.ts",
      content: emitModels(
        program.data,
        program.classes,
        program.protocols,
        program.choices,
      ),
    },
    {
      path: "src/generated/functions.ts",
      content: emitFunctions(
        program.functions,
        program.data,
        program.classes,
      ).replaceAll('from "./models"', 'from "./models.js"'),
    },
    {
      path: "src/generated/contracts.ts",
      content: emitContracts(program),
    },
    {
      path: "src/generated/validation.ts",
      content: emitValidation(),
    },
    {
      path: "src/generated/repositories.ts",
      content: emitRepositories(program),
    },
    {
      path: "src/generated/realtime.ts",
      content: emitRealtime(program),
    },
    {
      path: "src/generated/jobs.ts",
      content: emitJobs(program),
    },
    {
      path: "src/generated/server.ts",
      content: emitServer(program),
    },
    {
      path: "src/index.ts",
      content:
        'import { startEvermoreServers } from "./generated/server.js";\n' +
        'import { startEvermoreJobs } from "./generated/jobs.js";\n\n' +
        "startEvermoreJobs();\n" +
        "await startEvermoreServers();\n",
    },
    {
      path: "src/generated/evermore.server.json",
      content:
        JSON.stringify(
          {
            app: program.appName,
            target: "node",
            servers: program.servers.map((server) => ({
              name: server.name,
              port: server.port,
              endpoints: server.endpoints.map((endpoint) => ({
                method: endpoint.method,
                path: endpoint.path,
                request: endpoint.requestType
                  ? describeSchema(endpoint.requestType)
                  : null,
                response: describeSchema(endpoint.responseType),
                handler: endpoint.handler,
                auth: endpoint.auth,
              })),
              databases: server.databases,
              repositories: server.repositories,
              jobs: server.jobs,
              realtime: server.realtime.map((channel) => ({
                name: channel.name,
                message: describeSchema(channel.messageType),
              })),
            })),
          },
          null,
          2,
        ) + "\n",
    },
  ];

  return files;
}

function emitContracts(program: IRProgram): string {
  const lines = [
    "// Generated by Evermore. Do not edit by hand.",
    'import type { EvermoreModels } from "./models.js";',
    "",
    "export type EvermoreEndpointContracts = {",
  ];

  for (const server of program.servers) {
    for (const endpoint of server.endpoints) {
      const key = server.name + " " + endpoint.method + " " + endpoint.path;
      lines.push(
        "  " +
          JSON.stringify(key) +
          ": { readonly request: " +
          (endpoint.requestType
            ? emitTypeRef(endpoint.requestType)
            : "null") +
          "; readonly response: " +
          emitTypeRef(endpoint.responseType) +
          "; };",
      );
    }
  }

  lines.push("};", "", "export const evermoreContractSchemas = {");

  for (const [name, schema] of modelSchemas(program)) {
    lines.push("  " + JSON.stringify(name) + ": " + schema + ",");
  }

  lines.push("} as const;", "");
  return lines.join("\n");
}

function emitValidation(): string {
  return `// Generated by Evermore. Do not edit by hand.
export type ContractSchema =
  | { readonly kind: "primitive"; readonly name: "text" | "id" | "number" | "boolean" }
  | { readonly kind: "choice"; readonly cases: readonly string[] }
  | { readonly kind: "object"; readonly fields: Readonly<Record<string, ContractSchema>> }
  | { readonly kind: "list"; readonly element: ContractSchema }
  | { readonly kind: "set"; readonly element: ContractSchema }
  | { readonly kind: "map"; readonly key: ContractSchema; readonly value: ContractSchema }
  | { readonly kind: "optional"; readonly value: ContractSchema }
  | { readonly kind: "result"; readonly ok: ContractSchema; readonly error: ContractSchema }
  | { readonly kind: "named"; readonly name: string };

export function validateEvermoreValue(
  value: unknown,
  schema: ContractSchema,
  named: Readonly<Record<string, ContractSchema>>,
): boolean {
  switch (schema.kind) {
    case "primitive":
      if (schema.name === "number") return typeof value === "number" && Number.isFinite(value);
      if (schema.name === "boolean") return typeof value === "boolean";
      return typeof value === "string";
    case "choice":
      return typeof value === "string" && schema.cases.includes(value);
    case "object":
      return (
        typeof value === "object" &&
        value !== null &&
        Object.entries(schema.fields).every(([key, child]) =>
          validateEvermoreValue((value as Record<string, unknown>)[key], child, named),
        )
      );
    case "list":
      return Array.isArray(value) && value.every((item) => validateEvermoreValue(item, schema.element, named));
    case "set":
      return Array.isArray(value) && value.every((item) => validateEvermoreValue(item, schema.element, named));
    case "map":
      return (
        typeof value === "object" &&
        value !== null &&
        Object.entries(value).every(([key, child]) =>
          validateEvermoreValue(key, schema.key, named) &&
          validateEvermoreValue(child, schema.value, named),
        )
      );
    case "optional":
      return value === null || validateEvermoreValue(value, schema.value, named);
    case "result":
      return (
        typeof value === "object" &&
        value !== null &&
        (
          ((value as { kind?: unknown }).kind === "ok" &&
            validateEvermoreValue((value as { value?: unknown }).value, schema.ok, named)) ||
          ((value as { kind?: unknown }).kind === "error" &&
            validateEvermoreValue((value as { error?: unknown }).error, schema.error, named))
        )
      );
    case "named": {
      const target = named[schema.name];
      return target ? validateEvermoreValue(value, target, named) : false;
    }
  }
}
`;
}

function emitRepositories(program: IRProgram): string {
  const repositories = program.servers.flatMap((server) =>
    server.repositories.map((repository) => ({
      server,
      repository,
    })),
  );

  if (repositories.length === 0) {
    return (
      "// Generated by Evermore. Do not edit by hand.\n" +
      "export const evermoreRepositories = {} as const;\n"
    );
  }

  const lines = [
    "// Generated by Evermore. Do not edit by hand.",
    'import { Pool } from "pg";',
    'import type { EvermoreModels } from "./models.js";',
    "",
  ];

  for (const { server, repository } of repositories) {
    const className = safeName(repository.name) + "PostgresRepository";
    const modelType =
      'EvermoreModels[' + JSON.stringify(repository.modelName) + "]";
    const database = server.databases.find(
      (item) => item.name === repository.databaseName,
    );
    if (!database) continue;
    const table = "evermore_" + slug(repository.modelName);

    lines.push(
      "export interface " + safeName(repository.name) + "Repository {",
      "  list(): Promise<ReadonlyArray<" + modelType + ">>;",
      "  find(id: string): Promise<" + modelType + " | null>;",
      "  save(id: string, value: " + modelType + "): Promise<void>;",
      "}",
      "",
      "export class " + className + " implements " + safeName(repository.name) + "Repository {",
      "  private readonly pool: Pool;",
      "",
      "  constructor() {",
      "    const connectionString = process.env[" + JSON.stringify(database.connectionEnv) + "];",
      "    if (!connectionString) throw new Error(" +
        JSON.stringify("Missing required database environment variable " + database.connectionEnv) +
        ");",
      "    this.pool = new Pool({ connectionString });",
      "  }",
      "",
      "  async ensure(): Promise<void> {",
      "    await this.pool.query(" +
        JSON.stringify(
          'CREATE TABLE IF NOT EXISTS "' +
            table +
            '" (id text PRIMARY KEY, payload jsonb NOT NULL)',
        ) +
        ");",
      "  }",
      "",
      "  async list(): Promise<ReadonlyArray<" + modelType + ">> {",
      "    await this.ensure();",
      "    const result = await this.pool.query(" +
        JSON.stringify('SELECT payload FROM "' + table + '" ORDER BY id') +
        ");",
      "    return result.rows.map((row: { payload: " + modelType + " }) => row.payload);",
      "  }",
      "",
      "  async find(id: string): Promise<" + modelType + " | null> {",
      "    await this.ensure();",
      "    const result = await this.pool.query(" +
        JSON.stringify('SELECT payload FROM "' + table + '" WHERE id = $1') +
        ", [id]);",
      "    return (result.rows[0]?.payload as " + modelType + " | undefined) ?? null;",
      "  }",
      "",
      "  async save(id: string, value: " + modelType + "): Promise<void> {",
      "    await this.ensure();",
      "    await this.pool.query(" +
        JSON.stringify(
          'INSERT INTO "' +
            table +
            '" (id, payload) VALUES ($1, $2::jsonb) ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload',
        ) +
        ", [id, JSON.stringify(value)]);",
      "  }",
      "}",
      "",
    );
  }

  lines.push(
    "export const evermoreRepositories = {",
    ...repositories.map(
      ({ repository }) =>
        "  " +
        JSON.stringify(repository.name) +
        ": () => new " +
        safeName(repository.name) +
        "PostgresRepository(),",
    ),
    "} as const;",
    "",
  );

  return lines.join("\n");
}

function emitRealtime(program: IRProgram): string {
  const channels = program.servers.flatMap((server) =>
    server.realtime.map((channel) => ({
      server: server.name,
      channel,
    })),
  );

  const channelNames = channels.map(
    ({ server, channel }) => server + "." + channel.name,
  );

  return `// Generated by Evermore. Do not edit by hand.
import type { ServerResponse } from "node:http";

const clients = new Map<string, Set<ServerResponse>>(
  ${JSON.stringify(channelNames)}.map((name) => [name, new Set<ServerResponse>()]),
);

export function attachEvermoreRealtime(
  channel: string,
  response: ServerResponse,
): void {
  const bucket = clients.get(channel);
  if (!bucket) throw new Error("Unknown realtime channel " + channel);
  response.writeHead(200, {
    "content-type": "text/event-stream",
    "cache-control": "no-cache",
    connection: "keep-alive",
  });
  response.write(": connected\\n\\n");
  bucket.add(response);
  response.on("close", () => bucket.delete(response));
}

export function publishEvermoreRealtime(
  channel: string,
  value: unknown,
): void {
  const bucket = clients.get(channel);
  if (!bucket) throw new Error("Unknown realtime channel " + channel);
  const payload = "data: " + JSON.stringify(value) + "\\n\\n";
  for (const client of bucket) client.write(payload);
}
`;
}

function emitJobs(program: IRProgram): string {
  const jobs = program.servers.flatMap((server) =>
    server.jobs.map((job) => ({ server: server.name, job })),
  );

  const lines = [
    "// Generated by Evermore. Do not edit by hand.",
    'import cron from "node-cron";',
    'import { evermoreFunctions } from "./functions.js";',
    "",
    "export function startEvermoreJobs(): void {",
  ];

  if (jobs.length === 0) {
    lines.push("  // No scheduled jobs declared.");
  }

  for (const { server, job } of jobs) {
    lines.push(
      "  cron.schedule(" +
        JSON.stringify(job.schedule) +
        ", () => {",
      "    const handler = evermoreFunctions[" +
        JSON.stringify(job.handler) +
        "] as unknown as () => unknown;",
      "    void Promise.resolve(handler()).catch((error: unknown) => {",
      "      console.error(" +
        JSON.stringify("[Evermore job " + server + "." + job.name + "]") +
        ", error);",
      "    });",
      "  });",
    );
  }

  lines.push("}", "");
  return lines.join("\n");
}

function emitServer(program: IRProgram): string {
  const lines = [
    "// Generated by Evermore. Do not edit by hand.",
    'import { createServer, type IncomingMessage, type ServerResponse } from "node:http";',
    'import { evermoreFunctions } from "./functions.js";',
    'import { evermoreContractSchemas } from "./contracts.js";',
    'import { validateEvermoreValue, type ContractSchema } from "./validation.js";',
    'import { attachEvermoreRealtime } from "./realtime.js";',
    "",
    "async function readJson(request: IncomingMessage): Promise<unknown> {",
    '  let body = "";',
    '  for await (const chunk of request) body += String(chunk);',
    "  if (!body) return null;",
    "  return JSON.parse(body);",
    "}",
    "",
    "function sendJson(response: ServerResponse, status: number, value: unknown): void {",
    '  response.writeHead(status, { "content-type": "application/json; charset=utf-8" });',
    "  response.end(JSON.stringify(value));",
    "}",
    "",
    "function authorized(request: IncomingMessage): boolean {",
    '  const value = request.headers.authorization ?? "";',
    '  return /^Bearer\\s+\\S+$/.test(value);',
    "}",
    "",
    "export async function startEvermoreServers(): Promise<void> {",
  ];

  for (const server of program.servers) {
    lines.push(
      "  {",
      "    const server = createServer(async (request, response) => {",
      '      const method = request.method ?? "GET";',
      '      const url = new URL(request.url ?? "/", "http://evermore.local");',
    );

    for (const channel of server.realtime) {
      lines.push(
        "      if (method === \"GET\" && url.pathname === " +
          JSON.stringify("/realtime/" + slug(channel.name)) +
          ") {",
        "        attachEvermoreRealtime(" +
          JSON.stringify(server.name + "." + channel.name) +
          ", response);",
        "        return;",
        "      }",
      );
    }

    for (const endpoint of server.endpoints) {
      const handler =
        "evermoreFunctions[" + JSON.stringify(endpoint.handler) + "]";
      lines.push(
        "      if (method === " +
          JSON.stringify(endpoint.method) +
          " && url.pathname === " +
          JSON.stringify(endpoint.path) +
          ") {",
      );

      if (endpoint.auth === "bearer") {
        lines.push(
          "        if (!authorized(request)) {",
          '          sendJson(response, 401, { error: "unauthorized" });',
          "          return;",
          "        }",
        );
      }

      if (endpoint.requestType) {
        const schema = schemaExpression(endpoint.requestType);
        lines.push(
          "        const input = await readJson(request);",
          "        const requestSchema: ContractSchema = " + schema + ";",
          "        if (!validateEvermoreValue(input, requestSchema, evermoreContractSchemas)) {",
          '          sendJson(response, 400, { error: "invalid_request" });',
          "          return;",
          "        }",
          "        const handler = " +
            handler +
            " as unknown as (input: unknown) => unknown;",
          "        const output = await Promise.resolve(handler(input));",
        );
      } else {
        lines.push(
          "        const handler = " +
            handler +
            " as unknown as () => unknown;",
          "        const output = await Promise.resolve(handler());",
        );
      }

      lines.push(
        "        const responseSchema: ContractSchema = " +
          schemaExpression(endpoint.responseType) +
          ";",
        "        if (!validateEvermoreValue(output, responseSchema, evermoreContractSchemas)) {",
        '          sendJson(response, 500, { error: "invalid_handler_response" });',
        "          return;",
        "        }",
        "        sendJson(response, 200, output);",
        "        return;",
        "      }",
      );
    }

    lines.push(
      '      sendJson(response, 404, { error: "not_found" });',
      "    });",
      "    await new Promise<void>((resolve) => {",
      "      server.listen(" +
        server.port +
        ", () => {",
      "        console.log(" +
        JSON.stringify(
          "Evermore server " +
            server.name +
            " listening on http://localhost:" +
            server.port,
        ) +
        ");",
      "        resolve();",
      "      });",
      "    });",
      "  }",
    );
  }

  lines.push("}", "");
  return lines.join("\n");
}

function modelSchemas(
  program: IRProgram,
): ReadonlyArray<readonly [string, string]> {
  const result: Array<readonly [string, string]> = [];

  for (const model of program.data) {
    result.push([model.name, objectSchema(model)]);
  }

  for (const model of program.classes) {
    result.push([model.name, objectSchema(model, true)]);
  }

  for (const choice of program.choices) {
    result.push([
      choice.name,
      JSON.stringify({ kind: "choice", cases: choice.cases }),
    ]);
  }

  return result;
}

function objectSchema(
  model: IRDataModel | IRClassModel,
  classModel = false,
): string {
  const fields = Object.fromEntries(
    model.fields
      .filter(
        (field) =>
          !classModel ||
          !("visibility" in field) ||
          field.visibility === "public",
      )
      .map((field) => [field.name, schemaObject(field.type)]),
  );

  return JSON.stringify({ kind: "object", fields });
}

function schemaExpression(type: TypeRef): string {
  return JSON.stringify(schemaObject(type));
}

function schemaObject(type: TypeRef): unknown {
  switch (type.kind) {
    case "None":
      return { kind: "optional", value: { kind: "named", name: "__never" } };
    case "Primitive":
      return { kind: "primitive", name: type.name };
    case "Named":
    case "Protocol":
      return { kind: "named", name: type.name };
    case "Generic":
      return { kind: "named", name: type.name };
    case "List":
      return { kind: "list", element: schemaObject(type.elementType) };
    case "Set":
      return { kind: "set", element: schemaObject(type.elementType) };
    case "Map":
      return {
        kind: "map",
        key: schemaObject(type.keyType),
        value: schemaObject(type.valueType),
      };
    case "Optional":
      return { kind: "optional", value: schemaObject(type.valueType) };
    case "Result":
      return {
        kind: "result",
        ok: schemaObject(type.okType),
        error: schemaObject(type.errorType),
      };
  }
}

function describeSchema(type: TypeRef): unknown {
  return schemaObject(type);
}

function safeName(value: string): string {
  const normalized = value.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[A-Za-z_]/.test(normalized) ? normalized : "_" + normalized;
}

function slug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "evermore";
}
