import type {
  IRArray,
  IRDataModel,
  IRPipeline,
  IRProgram,
  IRPythonBridge,
} from "../ir.js";
import type { TypeRef } from "../types.js";
import type { GeneratedFile } from "./vue.js";

export function emitPython(program: IRProgram): readonly GeneratedFile[] {
  if (program.pipelines.length === 0) {
    throw new Error(
      "The python target requires at least one pipeline declaration.",
    );
  }

  return [
    {
      path: "requirements.txt",
      content: "numpy>=2.0\npandas>=2.2\n",
    },
    {
      path: "pyproject.toml",
      content:
        "[project]\n" +
        'name = "' +
        slug(program.appName) +
        '-data"\n' +
        'version = "0.0.0"\n' +
        'requires-python = ">=3.11"\n' +
        "dependencies = [\"numpy>=2.0\", \"pandas>=2.2\"]\n",
    },
    {
      path: "evermore_generated/__init__.py",
      content: "# Generated by Evermore.\n",
    },
    {
      path: "evermore_generated/contracts.py",
      content: emitContracts(program),
    },
    {
      path: "evermore_generated/datasets.py",
      content: emitDatasets(program),
    },
    {
      path: "evermore_generated/arrays.py",
      content: emitArrays(program.arrays),
    },
    {
      path: "evermore_generated/bridges.py",
      content: emitBridges(program.pythonBridges),
    },
    {
      path: "evermore_generated/tracking.py",
      content: emitTracking(),
    },
    {
      path: "evermore_generated/pipelines.py",
      content: emitPipelines(program),
    },
    {
      path: "run.py",
      content: emitRunner(program.pipelines),
    },
    {
      path: "evermore.data.json",
      content:
        JSON.stringify(
          {
            app: program.appName,
            target: "python",
            datasets: program.datasets,
            arrays: program.arrays,
            pythonBridges: program.pythonBridges.map((bridge) => ({
              name: bridge.name,
              input: bridge.inputType
                ? describeType(bridge.inputType)
                : null,
              output: describeType(bridge.outputType),
              module: bridge.moduleName,
              callable: bridge.callableName,
            })),
            pipelines: program.pipelines,
            provenance: {
              sourceHashes: "sha256",
              deterministicSeeds: true,
              tracking: "jsonl",
            },
          },
          null,
          2,
        ) + "\n",
    },
  ];
}

function emitContracts(program: IRProgram): string {
  const lines = [
    "# Generated by Evermore. Do not edit by hand.",
    "from __future__ import annotations",
    "",
    "from typing import Literal, NotRequired, TypedDict",
    "",
  ];

  for (const choice of program.choices) {
    lines.push(
      safeName(choice.name) +
        " = Literal[" +
        choice.cases.map((item) => JSON.stringify(item)).join(", ") +
        "]",
      "",
    );
  }

  for (const model of program.data) {
    lines.push(...emitTypedDict(model));
  }

  for (const model of program.classes) {
    lines.push(
      "class " + safeName(model.name) + "(TypedDict):",
    );
    const publicFields = model.fields.filter(
      (field) => field.visibility === "public",
    );
    if (publicFields.length === 0) {
      lines.push("    pass");
    } else {
      for (const field of publicFields) {
        lines.push(
          "    " +
            safeField(field.name) +
            ": " +
            pythonType(field.type),
        );
      }
    }
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

function emitTypedDict(model: IRDataModel): string[] {
  const lines = [
    "class " + safeName(model.name) + "(TypedDict):",
  ];

  if (model.fields.length === 0) {
    lines.push("    pass");
  } else {
    for (const field of model.fields) {
      lines.push(
        "    " +
          safeField(field.name) +
          ": " +
          pythonType(field.type),
      );
    }
  }

  lines.push("");
  return lines;
}

function emitDatasets(program: IRProgram): string {
  const lines = [
    "# Generated by Evermore. Do not edit by hand.",
    "from __future__ import annotations",
    "",
    "from hashlib import sha256",
    "from pathlib import Path",
    "from typing import Any, cast",
    "",
    "import pandas as pd",
    "",
    "from .contracts import *",
    "",
    "def _sha256(path: Path) -> str:",
    '    return sha256(path.read_bytes()).hexdigest()',
    "",
  ];

  for (const dataset of program.datasets) {
    const fn = safeName(dataset.name);
    const row = safeName(dataset.rowType);
    lines.push(
      "def load_" + fn + "() -> tuple[list[" + row + "], dict[str, Any]]:",
      "    path = Path(" + JSON.stringify(dataset.source) + ")",
      "    frame = pd.read_csv(path)",
      "    rows = cast(list[" + row + "], frame.to_dict(orient=\"records\"))",
      "    provenance: dict[str, Any] = {",
      '        "dataset": ' + JSON.stringify(dataset.name) + ",",
      '        "source": str(path),',
      '        "sha256": _sha256(path),',
      '        "rows": int(len(frame)),',
      '        "columns": [str(item) for item in frame.columns],',
      "    }",
      "    return rows, provenance",
      "",
    );
  }

  return lines.join("\n") + "\n";
}

function emitArrays(arrays: readonly IRArray[]): string {
  const lines = [
    "# Generated by Evermore. Do not edit by hand.",
    "from __future__ import annotations",
    "",
    "from typing import Any",
    "",
    "import numpy as np",
    "",
    "ARRAY_CONTRACTS: dict[str, dict[str, Any]] = {",
  ];

  for (const array of arrays) {
    lines.push(
      "    " +
        JSON.stringify(array.name) +
        ": {\"dtype\": " +
        JSON.stringify(array.dtype) +
        ", \"shape\": " +
        JSON.stringify(array.shape) +
        "},",
    );
  }

  lines.push(
    "}",
    "",
    "def validate_array(name: str, value: np.ndarray[Any, Any]) -> bool:",
    "    contract = ARRAY_CONTRACTS[name]",
    '    if str(value.dtype) != contract["dtype"]:',
    "        return False",
    '    expected = str(contract["shape"]).split(",")',
    "    if len(expected) != value.ndim:",
    "        return False",
    "    return all(part == \"*\" or int(part) == actual for part, actual in zip(expected, value.shape, strict=True))",
    "",
  );

  return lines.join("\n") + "\n";
}

function emitBridges(
  bridges: readonly IRPythonBridge[],
): string {
  const lines = [
    "# Generated by Evermore. Do not edit by hand.",
    "from __future__ import annotations",
    "",
    "from importlib import import_module",
    "from typing import Any, Callable, cast",
    "",
    "from .contracts import *",
    "",
  ];

  for (const bridge of bridges) {
    const fn = safeName(bridge.name);
    const output = pythonType(bridge.outputType);
    const callable =
      "cast(Callable[..., " +
      output +
      "], getattr(import_module(" +
      JSON.stringify(bridge.moduleName) +
      "), " +
      JSON.stringify(bridge.callableName) +
      "))";

    if (bridge.inputType) {
      lines.push(
        "def " +
          fn +
          "(value: " +
          pythonType(bridge.inputType) +
          ") -> " +
          output +
          ":",
        "    target = " + callable,
        "    return target(value)",
        "",
      );
    } else {
      lines.push(
        "def " + fn + "() -> " + output + ":",
        "    target = " + callable,
        "    return target()",
        "",
      );
    }
  }

  return lines.join("\n") + "\n";
}

function emitTracking(): string {
  return [
    "# Generated by Evermore. Do not edit by hand.",
    "from __future__ import annotations",
    "",
    "import json",
    "from datetime import datetime, timezone",
    "from pathlib import Path",
    "from typing import Any, Protocol",
    "",
    "class ExperimentTracker(Protocol):",
    "    def record(self, event: dict[str, Any]) -> None: ...",
    "",
    "class JsonlTracker:",
    "    def __init__(self, path: str) -> None:",
    "        self.path = Path(path)",
    "        self.path.parent.mkdir(parents=True, exist_ok=True)",
    "",
    "    def record(self, event: dict[str, Any]) -> None:",
    "        payload = {",
    '            "timestamp": datetime.now(timezone.utc).isoformat(),',
    "            **event,",
    "        }",
    '        with self.path.open("a", encoding="utf-8") as handle:',
    "            handle.write(json.dumps(payload, sort_keys=True, default=str) + \"\\n\")",
    "",
  ].join("\n");
}

function emitPipelines(program: IRProgram): string {
  const lines = [
    "# Generated by Evermore. Do not edit by hand.",
    "from __future__ import annotations",
    "",
    "import random",
    "from typing import Any",
    "",
    "import numpy as np",
    "",
    "from . import bridges, datasets",
    "from .tracking import JsonlTracker",
    "",
  ];

  for (const pipeline of program.pipelines) {
    const dataset = program.datasets.find(
      (item) => item.name === pipeline.datasetName,
    );
    if (!dataset) continue;

    lines.push(
      "def run_" + safeName(pipeline.name) + "() -> dict[str, Any]:",
      "    random.seed(" + pipeline.seed + ")",
      "    np.random.seed(" + pipeline.seed + ")",
      "    rows, provenance = datasets.load_" +
        safeName(dataset.name) +
        "()",
      "    artifact = bridges." +
        safeName(pipeline.trainBridge) +
        "(rows)",
      "    metrics = bridges." +
        safeName(pipeline.evaluateBridge) +
        "(artifact)",
      "    tracker = JsonlTracker(" +
        JSON.stringify(pipeline.tracking) +
        ")",
      "    event: dict[str, Any] = {",
      '        "pipeline": ' + JSON.stringify(pipeline.name) + ",",
      '        "seed": ' + pipeline.seed + ",",
      '        "provenance": provenance,',
      '        "metrics": metrics,',
      "    }",
      "    tracker.record(event)",
      "    return event",
      "",
    );
  }

  return lines.join("\n") + "\n";
}

function emitRunner(pipelines: readonly IRPipeline[]): string {
  const lines = [
    "# Generated by Evermore. Do not edit by hand.",
    "from evermore_generated import pipelines",
    "",
    "def main() -> None:",
  ];

  if (pipelines.length === 0) {
    lines.push("    pass");
  } else {
    for (const pipeline of pipelines) {
      lines.push(
        "    pipelines.run_" + safeName(pipeline.name) + "()",
      );
    }
  }

  lines.push("", 'if __name__ == "__main__":', "    main()", "");
  return lines.join("\n");
}

function pythonType(type: TypeRef): string {
  switch (type.kind) {
    case "None":
      return "None";
    case "Primitive":
      if (type.name === "number") return "float";
      if (type.name === "boolean") return "bool";
      return "str";
    case "Named":
    case "Protocol":
    case "Generic":
      return safeName(type.name);
    case "Applied":
      return (
        safeName(type.name) +
        "[" +
        type.arguments.map(pythonType).join(", ") +
        "]"
      );
    case "List":
      return "list[" + pythonType(type.elementType) + "]";
    case "Set":
      return "set[" + pythonType(type.elementType) + "]";
    case "Map":
      return (
        "dict[" +
        pythonType(type.keyType) +
        ", " +
        pythonType(type.valueType) +
        "]"
      );
    case "Optional":
      return pythonType(type.valueType) + " | None";
    case "Result":
      return (
        "dict[str, " +
        pythonType(type.okType) +
        " | " +
        pythonType(type.errorType) +
        "]"
      );
  }
}

function describeType(type: TypeRef): unknown {
  switch (type.kind) {
    case "None":
      return "none";
    case "Primitive":
      return type.name;
    case "Named":
    case "Protocol":
    case "Generic":
      return type.name;
    case "Applied":
      return {
        applied: type.name,
        arguments: type.arguments.map(describeType),
      };
    case "List":
      return { list: describeType(type.elementType) };
    case "Set":
      return { set: describeType(type.elementType) };
    case "Map":
      return {
        map: {
          key: describeType(type.keyType),
          value: describeType(type.valueType),
        },
      };
    case "Optional":
      return { optional: describeType(type.valueType) };
    case "Result":
      return {
        result: {
          ok: describeType(type.okType),
          error: describeType(type.errorType),
        },
      };
  }
}

function safeName(value: string): string {
  const clean = value.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[A-Za-z_]/.test(clean) ? clean : "_" + clean;
}

function safeField(value: string): string {
  return safeName(value);
}

function slug(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "evermore-data"
  );
}
