import type { SourceSpan } from "../ast.js";
import { EvermoreDiagnosticError } from "../diagnostics.js";
import { formatSource, type FormatStyle } from "../formatter.js";
import { lex, type Token } from "../lexer.js";
import { parse } from "../parser.js";
import { analyze } from "../semantic.js";

export type EditorPosition = {
  readonly line: number;
  readonly character: number;
};

export type EditorRange = {
  readonly start: EditorPosition;
  readonly end: EditorPosition;
};

export type EditorDiagnostic = {
  readonly code: string;
  readonly severity: 1 | 2;
  readonly message: string;
  readonly range: EditorRange;
  readonly source: "evermore";
};

export type TextEdit = {
  readonly range: EditorRange;
  readonly newText: string;
};

export const semanticTokenLegend = [
  "keyword",
  "string",
  "number",
  "type",
  "function",
  "variable",
  "operator",
] as const;

export function diagnosticsForSource(source: string): readonly EditorDiagnostic[] {
  try {
    const analysis = analyze(parse(source));
    return analysis.diagnostics.map(toEditorDiagnostic);
  } catch (error) {
    if (error instanceof EvermoreDiagnosticError) {
      return error.diagnostics.map(toEditorDiagnostic);
    }
    throw error;
  }
}

export function formatDocument(
  source: string,
  style: FormatStyle = "natural",
): string {
  return formatSource(source, style);
}

export function semanticTokensForSource(source: string): readonly number[] {
  const tokens = lex(source).filter((token) => token.kind !== "eof");
  const data: number[] = [];
  let previousLine = 0;
  let previousCharacter = 0;

  for (const token of tokens) {
    const line = Math.max(0, token.span.start.line - 1);
    const character = Math.max(0, token.span.start.column - 1);
    const deltaLine = line - previousLine;
    const deltaStart = deltaLine === 0 ? character - previousCharacter : character;
    const length = Math.max(1, token.span.end.offset - token.span.start.offset);
    data.push(deltaLine, deltaStart, length, semanticType(token), 0);
    previousLine = line;
    previousCharacter = character;
  }

  return data;
}

export function renameIdentifier(
  source: string,
  position: EditorPosition,
  newName: string,
): readonly TextEdit[] {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(newName)) return [];

  const offset = offsetAt(source, position);
  const tokens = lex(source);
  const selected = tokens.find(
    (token) =>
      token.kind === "identifier" &&
      token.span.start.offset <= offset &&
      offset <= token.span.end.offset,
  );

  if (!selected) return [];

  return tokens
    .filter(
      (token) =>
        token.kind === "identifier" &&
        token.lexeme === selected.lexeme,
    )
    .map((token) => ({
      range: toRange(token.span),
      newText: newName,
    }));
}

export function generateMarkdownDocumentation(source: string): string {
  const program = parse(source);
  const lines = [
    "# " + program.appName,
    "",
    "_Generated by Evermore tooling._",
    "",
  ];

  const sections: readonly [
    string,
    readonly { readonly name: string }[],
  ][] = [
    ["Data", program.data],
    ["Classes", program.classes],
    ["Protocols", program.protocols],
    ["Choices", program.choices],
    ["Functions", program.functions],
    ["Servers", program.servers],
    ["Tools", program.tools],
    ["Contexts", program.contexts],
    ["Agents", program.agents],
    ["Evaluations", program.evaluations],
    ["Mobile", program.mobiles],
    ["Datasets", program.datasets],
    ["Arrays", program.arrays],
    ["Python bridges", program.pythonBridges],
    ["Pipelines", program.pipelines],
    ["Deployments", program.deployments],
    ["Components", program.components],
    ["Screens", program.screens],
  ];

  for (const [title, declarations] of sections) {
    if (declarations.length === 0) continue;
    lines.push("## " + title, "");
    for (const declaration of declarations) {
      lines.push("- `" + declaration.name + "`");
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function documentEnd(source: string): EditorPosition {
  const lines = source.split("\n");
  return {
    line: Math.max(0, lines.length - 1),
    character: lines.at(-1)?.length ?? 0,
  };
}

function semanticType(token: Token): number {
  if (token.kind === "string") return 1;
  if (token.kind === "number") return 2;
  if (token.kind === "identifier") return 5;
  if (
    token.kind === "lbrace" ||
    token.kind === "rbrace" ||
    token.kind === "lparen" ||
    token.kind === "rparen" ||
    token.kind === "lbracket" ||
    token.kind === "rbracket" ||
    token.kind === "comma" ||
    token.kind === "colon" ||
    token.kind === "dot" ||
    token.kind === "equal" ||
    token.kind === "eqeq" ||
    token.kind === "neq" ||
    token.kind === "gt" ||
    token.kind === "gte" ||
    token.kind === "lt" ||
    token.kind === "lte" ||
    token.kind === "plus" ||
    token.kind === "minus" ||
    token.kind === "star" ||
    token.kind === "slash"
  ) {
    return 6;
  }
  return 0;
}

function toEditorDiagnostic(
  diagnostic: {
    readonly code: string;
    readonly severity: "error" | "warning";
    readonly message: string;
    readonly span: SourceSpan;
  },
): EditorDiagnostic {
  return {
    code: diagnostic.code,
    severity: diagnostic.severity === "error" ? 1 : 2,
    message: diagnostic.message,
    range: toRange(diagnostic.span),
    source: "evermore",
  };
}

function toRange(span: SourceSpan): EditorRange {
  return {
    start: {
      line: Math.max(0, span.start.line - 1),
      character: Math.max(0, span.start.column - 1),
    },
    end: {
      line: Math.max(0, span.end.line - 1),
      character: Math.max(0, span.end.column - 1),
    },
  };
}

function offsetAt(source: string, position: EditorPosition): number {
  const lines = source.split("\n");
  let offset = 0;
  for (let index = 0; index < position.line; index += 1) {
    offset += (lines[index]?.length ?? 0) + 1;
  }
  return offset + position.character;
}
